# Generated by Django 5.2.10 on 2026-02-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesVerse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='userdata/profile_pic/'),
        ),
    ]
