# Generated by Django 5.2.10 on 2026-02-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesVerse', '0003_userprofile_profile_pic_delete_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://i0.wp.com/upload.wikimedia.org/wikipedia/commons/a/ac/Default_pfp.jpg', null=True, upload_to='userdata/profile_pic'),
        ),
    ]
