# Generated by Django 5.2.10 on 2026-03-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesVerse', '0003_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionhouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productionhouse',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
