# Generated by Django 6.0.1 on 2026-03-07 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesVerse', '0004_productionhouse_email_productionhouse_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(choices=[('trailer', 'Trailer'), ('poster', 'Poster'), ('bts', 'Behind the Scenes'), ('clip', 'Clip'), ('interview', 'Interview'), ('banner', 'Banner / Ad')], default='trailer', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('ja', 'Japanese'), ('ko', 'Korean'), ('other', 'Other')], default='en', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='promotions/media/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='promotions/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='MoviesVerse.productionhouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
