# Generated by Django 6.0.1 on 2026-03-08 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesVerse', '0005_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='omdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/posters/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_movies', to='MoviesVerse.productionhouse'),
        ),
    ]
